name: Clipboard
version: 0.09
abstract: Cliboard - Copy and Paste with any OS
author: Ryan King <rking@sharpsaw.org
license: perl
distribution_type: module
requires:
  Spiffy: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
